# Generated by Django 5.0 on 2024-02-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_buy',
            name='size',
            field=models.CharField(default=6, max_length=20),
            preserve_default=False,
        ),
    ]
