# Generated by Django 5.0 on 2024-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_direct_buy_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct_buy',
            name='size',
            field=models.CharField(default=6, max_length=20),
        ),
    ]
