# Generated by Django 5.0 on 2024-02-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_direct_buy_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct_buy',
            name='size',
        ),
    ]
