# Generated by Django 5.0 on 2024-02-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cartitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_buy',
            name='size',
            field=models.CharField(default=6, max_length=20, null=True),
        ),
    ]
