# Generated by Django 5.0 on 2024-02-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_direct_buy_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct_buy',
            name='size',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
