# Generated by Django 5.0 on 2024-02-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_remove_cartitem_size_remove_direct_buy_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
