# Generated by Django 5.0 on 2024-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_cartitem_selected_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='direct_buy',
            name='selected_size',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
