# Generated by Django 5.0 on 2024-02-22 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_direct_buy_selected_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direct_buy',
            name='selected_size',
        ),
    ]
