# Generated by Django 5.0 on 2024-02-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_direct_buy_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direct_buy',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
