# Generated by Django 5.0 on 2024-02-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapatoapp', '0003_product_tbl_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'brands',
                'verbose_name_plural': 'brands',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='brand',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
