# Generated by Django 5.0 on 2024-02-21 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapatoapp', '0004_brand_product_tbl_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='size',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=5, null=True),
        ),
    ]
