# Generated by Django 5.0 on 2024-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zapatoapp', '0005_product_tbl_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tbl',
            name='size',
            field=models.CharField(choices=[('5', '5'), ('6', '6')], max_length=5, null=True),
        ),
    ]
